markdown: kramdown

permalink: pretty
exclude: ['README.md']

author: Daskalakis Manos
author_email: manosdaskalakis@protonmail.com
description: Personal site of filmaker Daskalakis Manos.

cloudinary_url: https://res.cloudinary.com/dc5qotzae/image/upload/
cloudinary_folder: daskalakismanos/
cloudinary_crop: w_100,h_100,c_crop/

sass:
  style: compressed

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: shooting
    values:
      layout: content
  - scope:
      path: ""
      type: music
    values:
      layout: content

collections:
  shooting:
    output: true
    permalink: /:collection/:path/
  music:
    output: true
    permalink: /:collection/:path/