markdown: kramdown

permalink: pretty
exclude: ['README.md']

author: Daskalakis Manos
author_email: manosdaskalakis@protonmail.com
description: Personal site of filmaker Daskalakis Manos.

sass:
  style: compressed

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: shooting
    values:
      layout: content
  - scope:
      path: ""
      type: music
    values:
      layout: content

collections:
  shooting:
    output: true
    permalink: /:collection/:path/
  music:
    output: true
    permalink: /:collection/:path/